export const ADD_QUALIFICATION = 'ADD_QUALIFICATION';
export const ADD_QUALIFICATION_SUCCESS = 'ADD_QUALIFICATION_SUCCESS';
export const ADD_QUALIFICATION_DUPLICATE = 'ADD_QUALIFICATION_DUPLICATE';
export const ADD_QUALIFICATION_FAILURE = 'ADD_QUALIFICATION_FAILURE';

export const FETCH_QUALIFICATION = 'FETCH_QUALIFICATION';
export const ADD_QUALIFICATION_SAGA = 'ADD_QUALIFICATION_SAGA';
export const FETCH_QUALIFICATION_SAGA = 'FETCH_QUALIFICATION_SAGA';
